steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'cf-test-cloudbuild', '--no-gen2', '--runtime=python38', '--region=europe-west1', '--source=.', '--entry-point=cf-test-cloudbuild', '--trigger-http']
