steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'cf-test-cloudbuild', '--no-gen2', '--region=europe-west1', '--runtime=python311', '--entry-point=cf-test-cloudbuild', '--trigger-http', '--source=.']
